# Spring properties
spring:
  application:
     name: Caching
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
# HTTP Server
server:
  port: 8087   # HTTP (Tomcat) port